# Generated by Django 4.2.7 on 2023-12-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
    ]
